Updates to game-service logic
CS4437-Big-Data-Management-Team-1/LMS-Development-Repo pull request #38
Opened 2024-11-14 15:40 UTC by LiamMoMurray

Added portion of the gameService logic

2024-11-14 18:28 UTC, olanhealy requested changes
Has this also been tested before pr made? A description on what happens, etc would be needed before approval

2024-11-14 18:28 UTC, olanhealy commented on game-service/src/main/java/com/lms/gameservice/controller/GameController.java
>              String uid = authService.validateToken(authorizationHeader);
keep spelling as 'authorisation' what has been done before

2024-11-14 18:28 UTC, olanhealy commented on game-service/src/main/java/com/lms/gameservice/controller/GameController.java
> +    public ResponseEntity<String> processRound(@PathVariable Long gameId) {
Not need to verify logged in? who calls process round? will system call will it be a cron job not really sure

2024-11-14 22:36 UTC, olanhealy commented
Is this and marks coming in together now? Failing the u
Job atm

2024-11-15 12:09 UTC, CaoimhinHawk1 approved these changes
Looks good to me, approving since its passing unit tests now, good work Liam, get back to Olan on his review and get this pushed ASAP!

2024-11-15 12:13 UTC, merged