Simple Email System Functioning
CS4437-Big-Data-Management-Team-1/LMS-Development-Repo pull request #6
Opened 2024-10-24 18:59 UTC by Whomstt

Run NotificationServiceApplication.java to send an email from lastmanstanding.notifier@gmail.com to itself / change recipient email in NotificationServiceApplication.java if you want to send it to another email for testing purposes.

2024-10-25 16:19 UTC, olanhealy commented on notification-service/.gitattributes
Not sure if needed

2024-10-25 16:19 UTC, olanhealy commented on notification-service/.mvn/wrapper/maven-wrapper.properties
Not sure again if needed

2024-10-25 16:19 UTC, olanhealy commented on notification-service/mvnw
again not sure if needed

2024-10-25 16:20 UTC, olanhealy commented on notification-service/mvnw.cmd
Not sure if needed

2024-10-25 16:21 UTC, olanhealy commented on notification-service/src/main/resources/application.properties
Dont think this info should have been committed? Maybe should just be in a .env for each of us we don't commit?

2024-10-25 16:22 UTC, olanhealy commented on notification-service/src/test/java/com/lms/notificationservice/NotificationServiceApplicationTests.java
May need to comment out in future something mvn clean install will not pass when you have methods written up and have test like this

2024-10-25 16:23 UTC, olanhealy requested changes
Very good for most part and is described as to design doc. Good work.
Just left small comments:
- Not sure some files are needed
- The application properties maybe shouldn't have that info on github

2024-10-25 18:02 UTC, Whomstt commented on notification-service/src/main/resources/application.properties
You're right. Deleted old app password and generated a new one that won't be committed. Now stored in env file.

2024-10-25 18:15 UTC, Whomstt commented on notification-service/src/test/java/com/lms/notificationservice/NotificationServiceApplicationTests.java
Commented out now

2024-10-25 19:23 UTC, olanhealy approved these changes
LGTM, good work

2024-10-26 14:06 UTC, CaoimheCahill commented
Looks good to me

2024-10-26 14:06 UTC, CaoimheCahill approved these changes

2024-10-26 14:16 UTC, merged